---
- name: Generate an HTML report from jinja template
  hosts: dil_uat_switches
  gather_facts: true
  vars:
    #email settings
    email_subject: Version Report
    email_host: 10.1.5.25
    email_from: reports@tower.npres.local
    email_to: b@xxx.com

    #random settings
    csv_path: /tmp
    csv_filename: report.csv
    headers: Hostname,Ver,uptime

  tasks:
  - ios_command: 
      commands: 
        - show running

  - name: Save CSV headers
    ansible.builtin.lineinfile:
      dest: "{{ csv_path }}/{{ csv_filename }}"
      line: "{{ headers }}"
      create: true
      state: present
    delegate_to: localhost
    run_once: true

  - name: Build out CSV file
    ansible.builtin.lineinfile:
      dest: "{{ csv_path }}/{{ csv_filename }}"
      line: "{{ inventory_hostname }},{{ ansible_distribution_version }},{{ ansible_kernel }},{{ rebooted.stdout }}"
      create: true
      state: present
    delegate_to: localhost

  - name: Read in CSV to variable
    community.general.read_csv:
      path: "{{ csv_path }}/{{ csv_filename }}"
    register: csv_file
    delegate_to: localhost
    run_once: true

#  - name: debug csv_file
#    debug:
#      var: csv_file
#    run_once: true

#  - name: Send Email
#    community.general.mail:
#      host: "{{ email_host }}"
#      from: "{{ email_from }}"
#      port: 25
#      to: "{{ email_to }}"
#      subject: "[Ansible] {{ email_subject }}"
#      body: "{{ lookup('template', 'report.html.j2') }}"
#      attach: "{{ csv_path }}/{{ csv_filename }}"
#      subtype: html
#    delegate_to: localhost
#    run_once: true
#